export const blogPosts = [
  {
    slug: "what-is-a-uuid",
    title: "What is a UUID and Why Do Developers Use It?",
    metaTitle: "What is a UUID? UUID v4 Explained for Developers",
    metaDescription:
      "Learn what a UUID is, how UUID v4 works, the difference between UUID and GUID, and when to use universally unique identifiers in your projects.",
    publishedAt: "2026-07-11",
    readingTime: 4,
    category: "Developer Guides",
    excerpt:
      "A UUID is a 128-bit identifier used across databases, APIs, and distributed systems to label records without coordinating with a central authority. Here is how it works and when to use it.",
    relatedToolSlug: "uuid-generator",
    relatedToolName: "UUID Generator",
    content: [
      { type: "p", text: "A UUID — Universally Unique Identifier — is a 128-bit value used to label records, objects, sessions, and transactions in software systems. A typical UUID looks like this: 550e8400-e29b-41d4-a716-446655440000. It is a 32-character hexadecimal string split into five groups by hyphens." },
      { type: "p", text: "Developers use UUIDs because they can be generated anywhere — on any server, any device, any programming language — without checking a central database first. Unlike sequential IDs (1, 2, 3...), two systems can each generate UUIDs independently and the values will not collide." },
      { type: "h2", text: "What makes UUID v4 different" },
      { type: "p", text: "There are multiple UUID versions, each using a different strategy to generate the identifier. UUID v4 is the most commonly used because it is entirely random. Out of its 128 bits, 122 are random and the remaining 6 are reserved to mark the version and variant. The probability of two UUID v4 values colliding is so low it is effectively impossible in practice." },
      { type: "p", text: "Other versions like v1 (time-based) or v5 (name-based hashing) are used in specific situations, but v4 is the safe default for most projects." },
      { type: "h2", text: "UUID vs GUID — are they the same?" },
      { type: "p", text: "GUID stands for Globally Unique Identifier. It is Microsoft's term for the same format. A UUID and a GUID are structurally identical and can be used interchangeably. If you are searching for a GUID generator, any UUID v4 tool produces valid GUIDs." },
      { type: "h2", text: "Common use cases" },
      { type: "ul", items: [
        "Database primary keys — especially in distributed systems where multiple servers insert records simultaneously",
        "API request IDs — for tracing requests across logs and debugging issues",
        "Session tokens — as part of user authentication flows",
        "Unique file names — for uploaded content to avoid naming collisions",
        "Idempotency keys — in payment systems to prevent duplicate transactions",
      ]},
      { type: "h2", text: "Hyphenated vs no-hyphens format" },
      { type: "p", text: "The standard UUID format includes hyphens: 550e8400-e29b-41d4-a716-446655440000. Some systems prefer the compact version without hyphens: 550e8400e29b41d4a716446655440000. Both represent the same value. The hyphens are a visual convention defined in the spec and carry no information themselves." },
      { type: "p", text: "Most databases and APIs accept both formats. Check your target system's documentation if you are unsure which to use. When in doubt, use the hyphenated form — it is the most widely recognised." },
    ],
  },
  {
    slug: "how-to-remove-line-breaks",
    title: "How to Remove Line Breaks from Text — And When You Need To",
    metaTitle: "How to Remove Line Breaks from Text Online",
    metaDescription:
      "Learn what line breaks are, why copied text often has unwanted line breaks, and how to remove them quickly using a free online tool.",
    publishedAt: "2026-07-11",
    readingTime: 3,
    category: "Text Tools",
    excerpt:
      "Copying text from PDFs, emails, or terminal output often leaves unwanted line breaks in the middle of sentences. Here is what causes them and how to fix them instantly.",
    relatedToolSlug: "line-break-remover",
    relatedToolName: "Line Break Remover",
    content: [
      { type: "p", text: "If you have ever copied text from a PDF, an email, a scanned document, or terminal output and pasted it somewhere else, you have probably encountered the problem: the text looks fine in the original but arrives with line breaks scattered through the middle of sentences. This makes it impossible to paste cleanly into a document, CMS, or API field without manual cleanup." },
      { type: "h2", text: "What are line breaks?" },
      { type: "p", text: "A line break is a hidden character that tells software to start a new line. There are three common types used across operating systems:" },
      { type: "ul", items: [
        "LF (Line Feed, \\n) — used by Linux and macOS",
        "CR (Carriage Return, \\r) — used by older Mac systems",
        "CRLF (\\r\\n) — used by Windows",
      ]},
      { type: "p", text: "When text is wrapped at a fixed column width (common in PDFs, emails, and terminal output), each line ends with one of these characters. When you copy and paste that text, the characters come along with it — and what looked like a visual wrap becomes a real line break embedded in your content." },
      { type: "h2", text: "When do you need to remove line breaks?" },
      { type: "ul", items: [
        "Copying paragraphs from a PDF into a document or email",
        "Cleaning up text scraped or exported from a website",
        "Preparing content for a CMS or text field that does not support multi-line input",
        "Processing email threads where each line wraps at 70 or 80 characters",
        "Reformatting data for CSV, JSON, or API payloads",
      ]},
      { type: "h2", text: "How to remove them manually" },
      { type: "p", text: "In most code editors, you can use Find & Replace with regex mode enabled. Search for \\n and replace with a space. In Microsoft Word, search for ^p (paragraph mark) or ^l (manual line break) and replace with a space. These methods work but require remembering the right syntax and toggling the right settings." },
      { type: "h2", text: "The faster way" },
      { type: "p", text: "An online line break remover lets you paste your text and clean it instantly — with options to replace breaks with a space, a comma, or remove them entirely. No regex knowledge needed, no editor settings to configure. Paste, remove, copy the result." },
    ],
  },
  {
    slug: "what-is-base64-encoding",
    title: "Base64 Encoding Explained: What It Is and When to Use It",
    metaTitle: "What is Base64 Encoding? A Plain-English Explanation",
    metaDescription:
      "Base64 encoding converts binary data into plain text so it can be safely transmitted over text-based systems. Learn what it is, how it works, and when to use it.",
    publishedAt: "2026-07-11",
    readingTime: 4,
    category: "Developer Guides",
    excerpt:
      "Base64 encoding converts binary data into a safe text format for transmission over systems that only handle text. It is used in data URIs, JWTs, email attachments, and API authentication.",
    relatedToolSlug: "base64-encoder-decoder",
    relatedToolName: "Base64 Encoder & Decoder",
    content: [
      { type: "p", text: "Base64 is an encoding scheme that converts binary data into a string of plain ASCII text. It was designed to allow binary content — like images, files, or arbitrary bytes — to travel safely through systems that were built to handle only text." },
      { type: "h2", text: "Why Base64 exists" },
      { type: "p", text: "Many protocols were designed decades ago when only text was transmitted — email (SMTP), HTTP headers, JSON fields, and XML documents are all text-based. If you try to embed raw binary data (like an image file) directly into a text field, the binary bytes will likely contain control characters that corrupt the transmission or break the parser." },
      { type: "p", text: "Base64 solves this by converting every 3 bytes of binary data into 4 printable ASCII characters using a fixed alphabet of 64 characters (A–Z, a–z, 0–9, +, /). The encoded output is always valid text, safe to include in any text-based format." },
      { type: "h2", text: "Common uses of Base64" },
      { type: "ul", items: [
        "Data URIs — embedding images directly into HTML or CSS as base64 strings to avoid separate HTTP requests",
        "JWTs (JSON Web Tokens) — the header and payload sections of a JWT are Base64-encoded JSON objects",
        "Email attachments — MIME encoding uses Base64 to attach binary files to email messages",
        "API authentication — Basic Auth credentials are sent as Base64-encoded username:password pairs",
        "Storing binary data in JSON — when an API needs to include binary content in a JSON response",
      ]},
      { type: "h2", text: "Base64 is not encryption" },
      { type: "p", text: "This is the most important thing to understand about Base64: it is an encoding, not encryption. Anyone can decode a Base64 string instantly — no key, no password required. Do not use Base64 to hide sensitive data. Use it only to safely transport binary data through text-based channels." },
      { type: "h2", text: "How to recognise Base64" },
      { type: "p", text: "Base64-encoded strings only contain letters, numbers, +, /, and = characters. They often end with one or two = signs (padding). They are typically longer than the original data by about 33%. If you see a long string of alphanumeric characters ending in == inside a JWT, a data URI, or an API response, it is almost certainly Base64." },
      { type: "h2", text: "URL-safe Base64" },
      { type: "p", text: "Standard Base64 uses + and / which have special meaning in URLs. URL-safe Base64 replaces + with - and / with _ so the encoded string can be used directly in URLs and query parameters without percent-encoding. JWTs use URL-safe Base64 for this reason." },
    ],
  },
  {
    slug: "what-is-url-encoding",
    title: "URL Encoding Explained: What Percent-Encoding Is and Why It Matters",
    metaTitle: "What is URL Encoding? Percent-Encoding Explained",
    metaDescription:
      "URL encoding converts special characters in URLs into a safe format using percent signs. Learn what it is, which characters need encoding, and how to encode and decode URLs online.",
    publishedAt: "2026-07-11",
    readingTime: 3,
    category: "Developer Guides",
    excerpt:
      "URLs can only contain a limited set of characters. URL encoding — also called percent-encoding — converts spaces, symbols, and non-ASCII characters into a format that URLs can safely carry.",
    relatedToolSlug: "url-encoder-decoder",
    relatedToolName: "URL Encoder and Decoder",
    content: [
      { type: "p", text: "A URL can only contain a specific set of characters defined by the URI specification. Letters (A–Z, a–z), digits (0–9), and a small set of symbols (-, _, ., ~) are safe to use as-is. Everything else — spaces, special characters, non-ASCII letters, and symbols like &, =, ?, # — must be encoded before they appear in a URL." },
      { type: "h2", text: "What percent-encoding does" },
      { type: "p", text: "Percent-encoding (also called URL encoding) converts an unsafe character into a % sign followed by its two-digit hexadecimal ASCII code. A space becomes %20. An ampersand (&) becomes %26. A forward slash in a query parameter becomes %2F. This allows any text to be safely embedded in a URL without breaking its structure." },
      { type: "h2", text: "Characters that must be encoded" },
      { type: "ul", items: [
        "Spaces → %20 (or + in form data)",
        "& → %26 (used as query parameter separator)",
        "= → %3D (used as key-value separator)",
        "? → %3F (marks the start of the query string)",
        "# → %23 (marks a fragment identifier)",
        "/ → %2F (path separator, when used inside a value)",
        "Non-ASCII characters — accented letters, emoji, Chinese characters",
      ]},
      { type: "h2", text: "When you need to encode a URL" },
      { type: "p", text: "The most common situation is building query parameters dynamically. If a user searches for \"hello world\", the search URL should be /search?q=hello%20world — not /search?q=hello world, which is technically invalid and may be misinterpreted." },
      { type: "p", text: "Other situations include passing file paths or email addresses as URL parameters, building redirect URLs that contain other URLs as values, and constructing API requests programmatically." },
      { type: "h2", text: "When you need to decode a URL" },
      { type: "p", text: "Decoding is useful when you receive an encoded URL and want to read the original content. API responses, server logs, browser address bars, and copied links often contain percent-encoded strings that are hard to read at a glance. Decoding reveals the original human-readable values." },
      { type: "h2", text: "URL encoding vs Base64" },
      { type: "p", text: "Both URL encoding and Base64 convert data for safe transmission, but they serve different purposes. URL encoding keeps text readable and URL-safe by replacing specific characters. Base64 converts binary data into a compact text format. Use URL encoding for query parameters and URL components. Use Base64 when you need to embed binary data like files or images." },
    ],
  },
  {
    slug: "regex-for-beginners",
    title: "Regex for Beginners: How to Use Regular Expressions",
    metaTitle: "Regex for Beginners — Regular Expressions Explained Simply",
    metaDescription:
      "Learn the basics of regular expressions (regex): what they are, how the syntax works, common patterns, and how to test them online.",
    publishedAt: "2026-07-11",
    readingTime: 5,
    category: "Developer Guides",
    excerpt:
      "Regular expressions let you search, match, and validate text using patterns. They look intimidating at first but follow a small set of rules. Here is how to get started.",
    relatedToolSlug: "regex-tester",
    relatedToolName: "Regex Tester",
    content: [
      { type: "p", text: "A regular expression (regex) is a pattern that describes a set of strings. Instead of searching for an exact word, you write a pattern that matches any text fitting a certain shape — for example, any string of digits, any email address, or any word starting with a capital letter." },
      { type: "p", text: "Regex is built into almost every programming language and text editor. Once you learn the basics, you can use the same patterns in JavaScript, Python, Go, VS Code find-and-replace, grep, and many other tools." },
      { type: "h2", text: "The essential syntax" },
      { type: "p", text: "Most regex patterns are combinations of literal characters and special metacharacters. Literal characters match themselves — the pattern cat matches the string \"cat\". Metacharacters have special meaning:" },
      { type: "ul", items: [
        ". (dot) — matches any single character except a newline",
        "* — matches the previous item zero or more times",
        "+ — matches the previous item one or more times",
        "? — matches the previous item zero or one time (makes it optional)",
        "[abc] — matches any one character inside the brackets (a, b, or c)",
        "[a-z] — matches any lowercase letter (a character range)",
        "^ — matches the start of the string",
        "$ — matches the end of the string",
        "\\d — matches any digit (0–9)",
        "\\w — matches any word character (letters, digits, underscore)",
        "\\s — matches any whitespace character (space, tab, newline)",
      ]},
      { type: "h2", text: "Practical examples" },
      { type: "p", text: "A pattern like \\d+ matches one or more digits — it would match \"42\", \"2026\", or \"100\" inside any string. The pattern [A-Z][a-z]+ matches a capital letter followed by one or more lowercase letters — useful for finding proper nouns. The pattern \\b\\w+@\\w+\\.\\w+\\b is a basic email pattern, though real email validation requires something more complete." },
      { type: "h2", text: "Flags change how the pattern works" },
      { type: "p", text: "Most regex engines support flags that modify matching behaviour. The g (global) flag finds all matches instead of stopping at the first one. The i (case-insensitive) flag makes [a-z] also match [A-Z]. The m (multiline) flag makes ^ and $ match the start and end of each line rather than the whole string." },
      { type: "h2", text: "Common mistakes" },
      { type: "ul", items: [
        "Forgetting to escape special characters — a literal dot should be \\. not . (which matches any character)",
        "Using .* greedily when you want a minimal match — use .*? for non-greedy matching",
        "Not anchoring patterns — without ^ and $, a pattern can match anywhere inside a longer string",
      ]},
      { type: "h2", text: "The best way to learn regex" },
      { type: "p", text: "The fastest way to learn regex is to write a pattern, test it against real text, and see what it matches and misses. An interactive regex tester lets you see matches highlighted in real time as you type the pattern, which makes the feedback loop immediate." },
    ],
  },
  {
    slug: "why-word-count-matters",
    title: "Why Word Count Matters: Writing, SEO, and Readability",
    metaTitle: "Why Word Count Matters for Writing and SEO",
    metaDescription:
      "Word count affects SEO, academic requirements, readability, and social media limits. Learn why it matters and how to track it effectively.",
    publishedAt: "2026-07-11",
    readingTime: 3,
    category: "Text Tools",
    excerpt:
      "Word count is more than a number. It affects how search engines rank your content, whether your essay meets requirements, and how long readers stay engaged.",
    relatedToolSlug: "word-counter",
    relatedToolName: "Word Counter",
    content: [
      { type: "p", text: "Word count is one of the most frequently checked writing metrics — yet it means something different depending on the context. A blog post writer tracking SEO length, a student hitting a minimum requirement, and a Twitter user counting characters before posting are all checking word count for different reasons." },
      { type: "h2", text: "Word count and SEO" },
      { type: "p", text: "Search engines do not rank content purely by length, but word count is correlated with ranking for a simple reason: comprehensive articles that cover a topic thoroughly tend to be longer, and they tend to rank better. For competitive informational queries, most top-ranking pages are between 1,200 and 2,500 words." },
      { type: "p", text: "This does not mean padding your content to hit a target. Thin content stretched to 2,000 words with filler still performs poorly. The goal is coverage — answering every question a reader might have about the topic. Word count is a side effect of doing that well, not a target in itself." },
      { type: "h2", text: "Academic and professional writing" },
      { type: "p", text: "Academic submissions, grant proposals, job applications, and press releases often have strict word limits or minimums. Tracking word count throughout writing (not just at the end) helps you pace the content and avoid having to cut or pad significantly at the last minute." },
      { type: "h2", text: "Reading time estimation" },
      { type: "p", text: "The average adult reads approximately 200–250 words per minute. A 1,000-word article takes about 4–5 minutes to read. Displaying estimated reading time at the top of an article sets reader expectations and reduces bounce rates — readers who know an article is a 3-minute read are more likely to commit to finishing it." },
      { type: "h2", text: "Character count for platforms with limits" },
      { type: "ul", items: [
        "X (Twitter) — 280 characters per post",
        "Instagram captions — 2,200 characters (first 125 shown before truncation)",
        "LinkedIn posts — 3,000 characters",
        "Google Ads headlines — 30 characters, descriptions — 90 characters",
        "Meta descriptions — recommended under 160 characters for search display",
      ]},
      { type: "h2", text: "Sentence and paragraph length" },
      { type: "p", text: "Short sentences and short paragraphs improve readability, especially on mobile screens. Aim for sentences under 20 words on average and paragraphs of 3–5 sentences maximum for web content. Tracking sentence count alongside word count helps identify when writing becomes too dense." },
    ],
  },
];

export const getBlogPost = (slug) => blogPosts.find((p) => p.slug === slug) ?? null;
