import { getMetadata } from "@/lib/metadata";

export const metadata = getMetadata({
  title: "Terms of Service – Toolzmint",
  description: "Terms of service for using Toolzmint's free online tools.",
  path: "/terms",
});

const TermsPage = () => {
  return (
    <div className="w-full max-w-3xl mx-auto py-12 px-4 space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground">Last updated: July 10, 2026</p>
      </div>

      <p className="text-muted-foreground leading-relaxed">
        By accessing or using Toolzmint (toolzmint.com), you agree to be bound
        by these Terms of Service. If you do not agree, please do not use the
        site.
      </p>

      <div className="space-y-3">
        <h2 className="text-xl font-semibold tracking-tight">Use of the service</h2>
        <p className="text-muted-foreground leading-relaxed">
          Toolzmint provides free browser-based utility tools for personal and
          professional use. You may use these tools for any lawful purpose. You
          agree not to use Toolzmint to process or distribute illegal, harmful,
          or malicious content.
        </p>
        <p className="text-muted-foreground leading-relaxed">
          You must not attempt to reverse engineer, scrape, overload, or interfere
          with the operation of this website or any of its tools.
        </p>
      </div>

      <div className="space-y-3">
        <h2 className="text-xl font-semibold tracking-tight">No account required</h2>
        <p className="text-muted-foreground leading-relaxed">
          Toolzmint does not require registration. All tools are available
          immediately and free of charge. We reserve the right to restrict access
          to the site if misuse is detected.
        </p>
      </div>

      <div className="space-y-3">
        <h2 className="text-xl font-semibold tracking-tight">Disclaimer of warranties</h2>
        <p className="text-muted-foreground leading-relaxed">
          All tools are provided "as is" and "as available" without any warranties
          of any kind, expressed or implied. We do not guarantee that the tools
          will be error-free, uninterrupted, or produce perfectly accurate results
          in all cases.
        </p>
        <p className="text-muted-foreground leading-relaxed">
          You are responsible for verifying the output of any tool before using
          it in critical applications.
        </p>
      </div>

      <div className="space-y-3">
        <h2 className="text-xl font-semibold tracking-tight">Limitation of liability</h2>
        <p className="text-muted-foreground leading-relaxed">
          To the fullest extent permitted by law, Toolzmint and its operators
          shall not be liable for any direct, indirect, incidental, special, or
          consequential damages resulting from the use or inability to use our
          tools, including but not limited to data loss, errors, or inaccuracies
          in output.
        </p>
      </div>

      <div className="space-y-3">
        <h2 className="text-xl font-semibold tracking-tight">Intellectual property</h2>
        <p className="text-muted-foreground leading-relaxed">
          The design, code, and content of Toolzmint are the property of
          Toolzmint. You may not reproduce, copy, or distribute any part of the
          site without permission. Output generated by tools (such as passwords,
          UUIDs, or converted text) is yours to use freely.
        </p>
      </div>

      <div className="space-y-3">
        <h2 className="text-xl font-semibold tracking-tight">Third-party services</h2>
        <p className="text-muted-foreground leading-relaxed">
          Toolzmint may display advertisements served by Google AdSense and may
          link to third-party websites. We are not responsible for the content,
          privacy practices, or accuracy of any third-party service.
        </p>
      </div>

      <div className="space-y-3">
        <h2 className="text-xl font-semibold tracking-tight">Changes to these terms</h2>
        <p className="text-muted-foreground leading-relaxed">
          We reserve the right to update these Terms of Service at any time.
          Changes take effect immediately upon posting. Continued use of the site
          after changes constitutes acceptance of the updated terms.
        </p>
      </div>

      <div className="space-y-3">
        <h2 className="text-xl font-semibold tracking-tight">Contact</h2>
        <p className="text-muted-foreground leading-relaxed">
          If you have questions about these Terms, contact us at{" "}
          <a href="mailto:support@toolzmint.com" className="text-primary underline">
            support@toolzmint.com
          </a>
          .
        </p>
      </div>
    </div>
  );
};

export default TermsPage;
